name: API Tests

on:
  push:
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Install newman
        run:  npm install -g newman

      - name: Run API tests
        run: newman run tests/restful-booker.postman_collection.json
